apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edge-clusters
  namespace: cattle-monitoring-system
  labels:
    cluster: edge-clusters
spec:
  endpoints:
    - interval: 1m
      honorLabels: true
      scrapeTimeout: 55s
      path: "/metrics"
      port: node-exporter
    - interval: 1m
      honorLabels: true
      scrapeTimeout: 55s
      path: "/metrics"
      port: kube-state-metrics
  namespaceSelector:
    matchNames:
      - cattle-monitoring-system
  selector:
    matchLabels:
      cluster: edge-clusters
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-one
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
spec:
  type: ExternalName
  externalName: 18.193.45.15
  clusterIP: ""
  ports:
    - port: 9100
      targetPort: 9100
      name: node-exporter
      protocol: TCP
    - port: 30080
      targetPort: 30080
      name: kube-state-metrics
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-one
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
subsets:
  - addresses:
      - ip: 18.193.45.15
    ports:
      - port: 9100
        name: node-exporter
        protocol: TCP
      - port: 30080
        name: kube-state-metrics
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-two
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
spec:
  type: ExternalName
  externalName: 34.246.200.66
  clusterIP: ""
  ports:
    - port: 9100
      targetPort: 9100
      name: node-exporter
      protocol: TCP
    - port: 30080
      targetPort: 30080
      name: kube-state-metrics
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-two
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
subsets:
  - addresses:
      - ip: 34.246.200.66
    ports:
      - port: 9100
        name: node-exporter
        protocol: TCP
      - port: 30080
        name: kube-state-metrics
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-three
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
spec:
  type: ExternalName
  externalName: 18.184.140.102
  clusterIP: ""
  ports:
    - port: 9100
      targetPort: 9100
      name: node-exporter
      protocol: TCP
    - port: 30080
      targetPort: 30080
      name: kube-state-metrics
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-three
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
subsets:
  - addresses:
      - ip: 18.184.140.102
    ports:
      - port: 9100
        name: node-exporter
        protocol: TCP
      - port: 30080
        name: kube-state-metrics
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-four
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
spec:
  type: ExternalName
  externalName: 3.249.228.211
  clusterIP: ""
  ports:
    - port: 9100
      targetPort: 9100
      name: node-exporter
      protocol: TCP
    - port: 30080
      targetPort: 30080
      name: kube-state-metrics
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-four
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
subsets:
  - addresses:
      - ip: 3.249.228.211
    ports:
      - port: 9100
        name: node-exporter
        protocol: TCP
      - port: 30080
        name: kube-state-metrics
        protocol: TCP